CREATE OR REPLACE VIEW v_f3_gr_bcv AS
 SELECT
 a.cod_presi,
 a.cod_entidad,
 a.cod_tipo_inst,
 a.cod_inst,
 a.ano,
 a.cod_partida,
 a.cod_generica,
 a.cod_especifica,
 a.cod_sub_espec,
 (substr(a.cod_partida::text, 1, 1) || '.'::text || substr(a.cod_partida::text, 2, 2) || '.'::text || mascara_cero(a.cod_generica) || '.'::text || mascara_cero(a.cod_especifica) || '.'::text || mascara_cero(a.cod_sub_espec)) AS codigo_completo,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=1)) as ejecutado_sector_01,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=2)) as ejecutado_sector_02,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=3)) as ejecutado_sector_03,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=4)) as ejecutado_sector_04,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=5)) as ejecutado_sector_05,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=6)) as ejecutado_sector_06,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=7)) as ejecutado_sector_07,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=8)) as ejecutado_sector_08,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=9)) as ejecutado_sector_09,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=10)) as ejecutado_sector_10,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=11)) as ejecutado_sector_11,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=12)) as ejecutado_sector_12,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=13)) as ejecutado_sector_13,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=14)) as ejecutado_sector_14,
 null_cero((SELECT sum(x.compromiso_ene + x.compromiso_feb + x.compromiso_mar + x.compromiso_abr + x.compromiso_may + x.compromiso_jun + x.compromiso_jul + x.compromiso_ago + x.compromiso_sep + x.compromiso_oct + x.compromiso_nov + x.compromiso_dic) FROM v_balance_ejecucion2 x WHERE x.cod_presi=a.cod_presi and x.cod_entidad=a.cod_entidad and x.cod_tipo_inst=a.cod_tipo_inst and x.ano=a.ano and x.cod_partida=a.cod_partida and x.cod_generica=a.cod_generica and x.cod_especifica=a.cod_especifica and x.cod_sub_espec=a.cod_sub_espec and x.cod_sector=15)) as ejecutado_sector_15

   FROM v_balance_ejecucion2 a
  GROUP BY a.cod_presi, a.cod_entidad, a.cod_tipo_inst, a.cod_inst, a.ano, a.cod_partida, a.cod_generica,a.cod_especifica,a.cod_sub_espec
  ORDER BY a.cod_presi, a.cod_entidad, a.cod_tipo_inst, a.cod_inst, a.ano, a.cod_partida, a.cod_generica,a.cod_especifica,a.cod_sub_espec;

ALTER TABLE v_f3_gr_bcv OWNER TO sisap;